# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file /home/casillserver/actions-runner-sam/sambot/discord-sam-jackson-bot/Dockerfile --tag sambot:$(date +%s)
    - name: Run the Docker image
      run: docker run -d --name sambot:$(date +%s) sambot
